# Generated by Django 2.1 on 2018-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20180919_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='URLfield',
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Url info'),
        ),
    ]
